url: https://smash.rs
excerpt_separator: '&lt;!--resumo--&gt;'

#baseurl: '/smash-rs'

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# gems
gems:
  - jekyll-paginate

# jekyll-paginate configs
paginate: 5
# paginate_path: '/page:num'

# sass
sass:
  style: compressed

# Exclude from Jekyll build
exclude:
  - Gemfile
  - LICENSE
  - README
  - "*.sublime-*"

future: true